import type { Metadata } from "next";
import type { CSSProperties } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "@/context/UserContext";
import { CartProvider } from "@/context/CartContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { getThemePrimary } from "@/lib/repos/appSettings";
import { buildBrandCssVars } from "@/lib/theme/brandCssVars";
import { SettingsProvider } from "@/context/SettingsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themePrimary = await getThemePrimary();
  const brandStyle = buildBrandCssVars(themePrimary) as CSSProperties;

  return (
    <html lang="es" style={brandStyle} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=localStorage.getItem('app-theme')||'dark';document.documentElement.classList.add(t==='light'?'light':'dark');})();`,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-canvas text-fg`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <SettingsProvider>
            <UserProvider>
              <CartProvider>{children}</CartProvider>
              <Toaster />
            </UserProvider>
          </SettingsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
