import type { Metadata } from "next";
import type { CSSProperties } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "@/context/UserContext";
import { CartProvider } from "@/context/CartContext";
import { getThemePrimary } from "@/lib/repos/appSettings";
import { buildBrandCssVars } from "@/lib/theme/brandCssVars";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themePrimary = await getThemePrimary();
  const brandStyle = buildBrandCssVars(themePrimary) as CSSProperties;

  return (
    <html
      lang="es"
      className="dark"
      style={brandStyle}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <UserProvider>
          <CartProvider>{children}</CartProvider>
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
